version: "3"

services:

  gtt:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: gtt
      REDMINE_DB_PASSWORD: gtt
      REDMINE_DB_DATABASE: gtt
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/log:/usr/src/redmine/log
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/public/themes:/usr/src/redmine/public/themes
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgis/postgis:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gtt
      POSTGRES_PASSWORD: gtt
      POSTGRES_DB: gtt
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: on-failure

volumes:
  gtt:
  postgres:
