version: "3"

services:

  gtt:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        REDMINE_VERSION: 4.0.7
        REDMICA_VERSION: ""
        GEM_PG_VERSION: 1.1.4
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: gtt
      REDMINE_DB_PASSWORD: gtt
      REDMINE_DB_DATABASE: gtt
      REDMINE_PLUGINS_MIGRATE: 1
      GEM_PG_VERSION: 1.1.4
    volumes:
      - ./files:/usr/src/redmine/files
      - ./plugins:/usr/src/redmine/plugins
      - ./public/themes:/usr/src/redmine/public/themes
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: gtt
      POSTGRES_PASSWORD: gtt
      POSTGRES_DB: gtt
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure

volumes:
  gtt:
  postgres:
